Repository denpufa/Bank-System-for-DIM0517-UFRN, pull requests merged in 2021-07, with the labels that each got.

#2 create a intregation build with github action
  .github/workflows/flutter_test.yml
Labels: enhancement

#3 new: software arch
  .github/workflows/flutter_test.yml
  lib/back_end/models/account.dart
  lib/back_end/operations.dart
  lib/main.dart
  lib/pages/home_page.dart
  lib/routes.dart
  test/account_test.dart
  test/widget_test.dart
Labels: enhancement

#5 Feature/create accounts
  lib/back_end/data.dart
  lib/back_end/models/account.dart
  lib/back_end/operations.dart
  lib/main.dart
  lib/pages/create_page.dart
  lib/pages/home_page.dart
  lib/routes.dart
  test/account_test.dart
  test/operations_test.dart
  test/widget_test.dart
Labels: enhancement

#7 Feature/create accounts
  lib/back_end/data.dart
  lib/back_end/operations.dart
  lib/main.dart
  lib/pages/create_page.dart
  lib/pages/home_page.dart
  lib/routes.dart
  test/account_test.dart
  test/operations_test.dart
Labels: enhancement

#10 balance query function was added
  lib/back_end/operations.dart
  lib/main.dart
  lib/pages/consult_balance_page.dart
  lib/pages/home_page.dart
  lib/pages/operations_page.dart
  lib/routes.dart
  test/operations_test.dart
Labels: enhancement

#11 Feature/credit
  lib/back_end/data.dart
  lib/back_end/models/account.dart
  lib/back_end/operations.dart
  lib/main.dart
  lib/pages/consult_balance_page.dart
  lib/pages/create_page.dart
  lib/pages/credit_page.dart
  lib/pages/home_page.dart
  lib/pages/operations_page.dart
  lib/routes.dart
  test/account_test.dart
  test/operations_test.dart
  test/widget_test.dart
Labels: duplicate, enhancement

#12 add layout HomePage
  assets/images/logo.svg
  assets/images/person.png
  lib/main.dart
  lib/pages/home_page.dart
  lib/shared/themes/app_colors.dart
  lib/shared/themes/app_images.dart
  lib/shared/themes/app_text_styles.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#21 fix: correct parts and import
  lib/main.dart
  test/operations_test.dart
Labels: bug
